# Generated by Django 4.2.4 on 2023-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="preamble",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="preamble"
            ),
        ),
    ]
