# Generated by Django 4.2.4 on 2023-09-16 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_courses_lesson_courseteachers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-create_date",),
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
