# Generated by Django 4.2.4 on 2023-09-16 16:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_alter_news_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseteachers",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("course", "num"),
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
    ]
